apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ingress
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: bsgroups/test-kongingress:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1323
---
apiVersion: v1
kind: Service
metadata:
  name: test-ingress
  labels:
    app: test-app
spec:
  selector:
    app: test-app
  ports:
  - port: 1323
    name: test-svc
    targetPort: 1323
---

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: test-kongingress-rule
upstream:
  hash_on: none
  hash_fallback: none
  healthchecks:
    active:
      concurrency: 10
      healthy:
        http_statuses:
        - 200
        - 302
        interval: 2
        successes: 2
      http_path: "/health"
      timeout: 1
      unhealthy:
        http_statuses:
        - 429
        - 404
        - 500
        - 501
        - 502
        - 503
        - 504
        - 505
        interval: 2
        http_failures: 2
        tcp_failures: 3
        timeouts: 5
    passive:
      healthy:
        http_statuses:
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 226
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        successes: 1
      unhealthy:
        http_failures: 3
        http_statuses:
        - 429
        - 500
        - 503
        tcp_failures: 3
        timeouts: 1
    slots: 1000
proxy:
  protocol: http
  path: /sub-path
  connect_timeout: 10000
  retries: 10
  read_timeout: 10000
  write_timeout: 10000
route:
  methods:
  - POST
  - GET
  - OPTIONS
  regex_priority: 0
  strip_path: true
  preserve_host: true
  protocols:
  - http
  - https
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-kongingress-rule
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /test/ingress
        backend:
          serviceName: test-ingress
          servicePort: test-svc